### ISSUE TITLE
About removing - resetting a migration request

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/DBS#467]
Hi @yuyiguo 
Could you please look at this ticket?
https://ggus.eu/index.php?mode=ticket_info&ticket_id=112709
Thanks

**Comment by yuyiguo** [comment]
Hi, @julianbadillo 

This is an old DS. https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets?detail=1&dataset=/SMS-TChiWZ_mChi20-100to500_mChi10_0to200-MG/Summer12-START53_V19_FSIM_UFL/USER
shows me that the DS is already in PROD.

https://cmsweb.cern.ch/dbs/prod/global/DBSMigrate/status?migration_rqst_id=120003
show the migration was failed Permanently.  What error message did you get when you submitted?

Did you use this API to remove the migration https://cms-http-group.web.cern.ch/cms-http-group/apidoc/dbs3-client/current/dbs.apis.html?highlight=remove#dbs.apis.dbsClient.DbsApi.removeMigration ?

**Comment by julianbadillo** [comment]
Hi @yuyiguo 
So the dataset is already in production?
When I try to query files or blocks on DAS I get an empty reply:
https://cmsweb.cern.ch/das/request?input=file%20dataset%3D/SMS-TChiWZ_mChi20-100to500_mChi10_0to200-MG/Summer12-START53_V19_FSIM_UFL/USER&instance=prod/global&idx=0&limit=10

The error message I got was simply "request failed", and error code = 9

Yes I used the dbs3 API

**Comment by yuyiguo** [comment]
@ericvaandering , @belforte 

Hi, @julianbadillo :
I added @belforte and @ericvaandering. They might have better idea on how to handle this problem. 

After debugging the dataset, I found the problem was that the dataset on phys01 is invalid in DBS3 world. I guess it was migrated from dbs2 local1 to phys01.

The basic problem was that the dataset was not registered to DBS correctly. This DS has one block and a bunch of files. The files have configurations registered to DBS as well as the dataset that should have all the configuration its files have, However, the migration server complained about one of the configuration was missing so this was a wrong source data to the migration server. The migration failed  permanently with code 9. This means resubmit it will fail again because it is an error in source data. I confirmed it by using direct sqls on the database.

Because of this problem the migration server could not bring in the block and files into the PROD, but an empty dataset. I don't think I can fix the problem because it is wrong data. My suggestion would be you rerun the job to produce the correct data in phys03, then migrate it into PROD.

Sorry about the bad news.

Yuyi

**Comment by ericvaandering** [comment]
Had a quick chat with @yuyiguo . My first thought was to have the user run over the dataset with CRAB and (basically just read and write everything, no analysis) and publish the output in to phys03. This may not work out of the box since CRAB may try to migrate the troublesome dateset from phys01 to phys03. But is there a CRAB2 option to discard the parentage?

Second thought was to use CRAB3's "run on a list of files" option to do much the same thing: generate an equivalent dateset in phys03 with no parentage.

Either of these should be able to be migrated and StoreResults-ed. I suspect if this data is from the DBS2 era, asking the user to reproduce it from first principles is not going to be possible.

**Comment by belforte** [comment]
Yes.  Will figure out crab details when I can read the full thread 
On Apr 21, 2015 5:38 PM, Eric Vaandering <notifications@github.com> wrote:Had a quick chat with @yuyiguo . My first thought was to have the user run over the dataset with CRAB and (basically just read and write everything, no analysis) and publish the output in to phys03. This may not work out of the box since CRAB may try to migrate the troublesome dateset from phys01 to phys03. But is there a CRAB2 option to discard the parentage?

Second thought was to use CRAB3's "run on a list of files" option to do much the same thing: generate an equivalent dateset in phys03 with no parentage.

Either of these should be able to be migrated and StoreResults-ed. I suspect if this data is from the DBS2 era, asking the user to reproduce it from first principles is not going to be possible.

**Comment by yuyiguo** [comment]
Done.
