### ISSUE TITLE
listFileLumi and ListFileLumiArray

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#484]
@AndresTanasijczuk 
listFileLumiArray DBS client API should add searching on block_name that is implemented on the server side API. 

listFileLumis client API document should add lfn list and common on the list length cannot exceed the total URL allowed length. The API works with list of lfns.

Andres Tanasijczuk gave a list of test results as below:
Let me give more details about when the listFileLumis and listFileLumiArray methods did or didn't return me the lumis information in my example dataset:
listFileLumiArray(logical_file_name=LFN, validFileOnly = 1) NO (not even for the valid file)
listFileLumiArray(logical_file_name=LFN, validFileOnly = 0) YES (for all the files)
listFileLumiArray(logical_file_name=LFN) YES (for all the files)
listFileLumiArray(logical_file_name=list(LFNs in block), validFileOnly = 1) NO (not even for the valid file)
listFileLumiArray(logical_file_name=list(LFNs in block), validFileOnly = 0) YES (for all the files)
listFileLumiArray(logical_file_name=list(LFNs in block)) YES (for all the files)
listFileLumis(logical_file_name=LFN, validFileOnly = 1) NO (not even for the valid file)
listFileLumis(logical_file_name=LFN, validFileOnly = 0) YES (for all the files)
listFileLumis(logical_file_name=LFN) YES (for all the files)
listFileLumis(block_name=blockName, validFileOnly = 1) NO (not even for the valid file)
listFileLumis(block_name=blockName, validFileOnly = 0) NO (not even for the valid file) <---- This is wrong IMO; should give me the info for all files.
listFileLumis(block_name=blockName) YES (for all the files)

**Comment by AndresTanasijczuk** [comment]
The dataset I used for testing listFileLumis and listFileLumiArray is this one (available in phys03 DBS instance): /GenericTTbar/atanasi-140429_131619_crab_AprilTest_3000jbsOf3hrs-95e5dc29a1ac0766eb8514eb5d4ff77a/USER 
DAS link: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2FGenericTTbar%2Fatanasi-140429_131619_crab_AprilTest_3000jbsOf3hrs-95e5dc29a1ac0766eb8514eb5d4ff77a%2FUSER

The dataset has 1965 files in 20 blocks. The dataset had originally access type 'VALID' (and all files in valid state). But I used the following procedure to invalidate the dataset (which invalidates all the files as well) and then to change 1 file to 'valid' state:
1) cmsenv + setup the CRAB2 environment (in lxplus)
2) python $CRABPYTHON/DBS3SetDatasetStatus.py --dataset=/GenericTTbar/atanasi-140429_131619_crab_AprilTest_3000jbsOf3hrs-95e5dc29a1ac0766eb8514eb5d4ff77a/USER --url=https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter --status=INVALID --recursive=False
3) python $CRABPYTHON/DBS3SetFileStatus.py --url=https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter --status=valid --recursive=False  --files=/store/user/atanasi/GenericTTbar/140429_131619_crab_AprilTest_3000jbsOf3hrs/140429_131619/0000/MyTTBarTauolaTest_1.root

So I ended up with an INVALID dataset, with 1964 files in invalid state and 1 file in valid state. The valid file belongs to block /GenericTTbar/atanasi-140429_131619_crab_AprilTest_3000jbsOf3hrs-95e5dc29a1ac0766eb8514eb5d4ff77a/USER#c4dea6b6-3e26-4d3a-a6c4-ab1a5b0a5f4c. This block has 65 files (64 in invalid state). Since the dataset access type is INVALID (i.e. is not VALID or PRODUCTION) it is expected that when I set validFileOnly=1 I didn't get back the lumis info (got an empty list). The only problem I wanted to report is that listFileLumis(block_name=blockName, validFileOnly = 0) returned me an empty list (for all the 20 blocks), while listFileLumis(block_name=blockName) returned me the lumis info as expected (for all the 20 blocks). But not passing the validFileOnly argument should be the same as passing it with value 0, right?

For my tests I was using WMCore's listDatasetFileDetails method: https://github.com/dmwm/WMCore/blob/1.0.8.pre7/src/python/WMCore/Services/DBS/DBS3Reader.py#L224, but:
1) replacing in https://github.com/dmwm/WMCore/blob/1.0.8.pre7/src/python/WMCore/Services/DBS/DBS3Reader.py#L243 validFileOnly = 0 (although this is not relevant for the tests);
2) replacing https://github.com/dmwm/WMCore/blob/1.0.8.pre7/src/python/WMCore/Services/DBS/DBS3Reader.py#L263 by:
a) file_lumis = self.dbs.listFileLumis(block_name=blockName, validFileOnly = 1)
b) file_lumis = self.dbs.listFileLumis(block_name=blockName, validFileOnly = 0)
c) file_lumis = self.dbs.listFileLumis(block_name=blockName)
d) other replacements to query per file
And as I said, 2b) returned file_lumis = [] for all the 20 blocks, while 2c) returned me the right lumis info.

**Comment by yuyiguo** [comment]
@AndresTanasijczuk 

I have update the client and server doc to indicate the max list length of input vairables, such as logical_file_name, run or lumi is 1000.

In deed there was a bug in the sever when check for the validFileOlny flag. The variables in the url is a string so need to convert it into int before checking. After I fixed it, the flag is working as expected. I will have the fix in Dec release.

**Comment by yuyiguo** [comment]
Will close it when PR created.
