### ISSUE TITLE
listFileArray disable run_num=1 search 

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#506]
it is a full table scan of file_lumi table if run_num=1. We should check the input for run_num=1 and signal it as an invalid input. Need to update the document too.

**Comment by yuyiguo** [comment]
@amaltaro, @ticoann 
Are you guys modify WMAgent code in the upcoming release? I am going to implement this issue.

**Comment by amaltaro** [comment]
@yuyiguo listFileArray will only support run_num=1 when we pass a logical_file_name in the call, right? It should fail for either block or dataset in the call (?)

@ticoann , if you still didn't start this work. I'm happy to do so this Thursday.

**Comment by yuyiguo** [comment]
Yes, Alan.

**Comment by amaltaro** [comment]
@yuyiguo , right now (cmsweb production with 3.3.120 dbsclient) I *cannot* make this query:
```dbsApi.listFileArray(block_name=block.get('block_name'), run_num=1, detail=True)```
because I get this error message:
dbs.exceptions.dbsClientException.dbsClientException: 'Invalid input: files API does not supprt run_num=1 when no lumi.'

However, if I do not provide the run_num parameter, it works just fine, either with block_name or with dataset. Can you confirm these cases will be kept valid please?

**Comment by yuyiguo** [comment]
@amaltaro This is the correct behavior. In the current version we allow searching with run_num=1 as long as lumi section number is provided when searching on dataset/block. With the next release, we will turn of run_num=1 searching no matter lumi section is provided or not when searching on dataset/block.

**Comment by yuyiguo** [comment]
Done
