### ISSUE TITLE
Inconsistent data types in filessummaries (and may in other APIs).

### ISSUE THREAD

**Issue by vkuznet** [dmwm/DBS#513]
Yuyi, filesummaries returns inconsistent data types which cause problem at client side (DAS) which parse its output. Here are two different results:
```
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries/?dataset=/WToENu_Tune4C_13TeV-pythia8/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW
[{"num_file": 61, "num_lumi": 1103, "num_block": 1, "num_event": 99280, "file_size": 180558658981}]
```
the return type here is list and element of a list is dictionary.

While if I do another call I get this
```
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries/?dataset=/GluGluToHToWWTo2LAndTau2Nu_M-115_8TeV-minloHJJ-pythia6-tauola/None-v0/GEN-SIM&validFileOnly=1
[null]
```
here return type is list whose element is null.

The difference in two cases is subtle but important. In former case you return dict within a list, while in second case your return null. And, null != dict as data type concern.
Please fix that behavior. I would appreciate if you look up all other APIs for such misbehavior and see if returned data have consistent data types.
Thanks,
Valentin.

**Comment by yuyiguo** [comment]
Valentin, 

I will check the APIs when sql queries return NULL. Is it OK with you that we have the fixing in April release?
Thanks,
Yuyi

**Comment by vkuznet** [comment]
Yuyi,
yes, that's fine, I rather prefer that you'll check all APIs then fix one
specific one and declare the victory. I don't know how many APIs are affected,
but I did find that filesummaries is certainly returning different data types
as I described.
Best,
Valentin.

**Comment by amaltaro** [comment]
And I was about to open the same issue reported here, e.g.:
`
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/filesummaries?dataset=/QCD_Pt-40toInf_fwdJet_bwdJet_Tune4C_2p76TeV-pythia8/DMWM_Test-MonteCarlo_eff_HG1606_Validation_TEST_Alan_v2-v1/GEN-SIM
`
which returns `[null]`.

Yuyi, if you have no time to look at all the apis, I suggest you fix at least those known to be wrong.
If people face the same problem elsewhere, they will certainly report :)

**Comment by yuyiguo** [comment]
@vkuznet 
ideally, when nothing is found in DBS, DBS should return [ ]. Currently it returns [None] as you reported in this issue.

For filessummaries API,  the code checks if anything was found. If not, it return {} as in below code. 
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/business/DBSFile.py#L91
This way the API will return [{}] as the result if nothing is found. Is this acceptable? 

In the past, above code  was "yield " instead "yield {}". Then [None] was returned. 

Since we are using generator here, the very top code just iterate over this generator and yield again to send a list as the final result. The final  list is created by below code:
https://github.com/dmwm/DBS/blob/3bc703ecf8e3096d9151000c765078981d98aee0/Server/Python/src/dbs/web/DBSReaderModel.py#L995 .
I did not get how to form an empty list [ ] using generator when nothing is found.

**Comment by vkuznet** [comment]
Yuyi,

> For filessummaries API,  the code checks if anything was found. If not, it return {} as in below code. 
> https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/business/DBSFile.py#L91

why on line 91 you need to yield {} at all? just put pass and don't yield.

> This way the API will return [{}] as the result if nothing is found. Is this acceptable? 

this would be acceptable since it will provide correct data type, i.e. a dict.
> 
> Since we are using generator here, the very top code just iterate over this generator and yield again to send a list as the final result. The final  list is created by below code:
> https://github.com/dmwm/DBS/blob/3bc703ecf8e3096d9151000c765078981d98aee0/Server/Python/src/dbs/web/DBSReaderModel.py#L995 .

This code can do one more check

```
for item in r:
    if item:
       yield item
```

> I did not get how to form an empty list [ ] using generator when nothing is found. 

see above, if nothing is found don't yield

**Comment by yuyiguo** [comment]
Thanks.

**Comment by yuyiguo** [comment]
Now return [] when nothing is found.

**Comment by amaltaro** [comment]
Awesome! Thanks, Yuyi.
