### ISSUE TITLE
Review and update DBS APIs to reject /*/*/* for dataset, block_name and lfn

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#525]
This query:
/dbs/prod/global/DBSReader/datasets/?run_num=281728&detail=True&dataset_access_type=VALID&dataset=/_/_/*. 

caused timeout because the dataset part. We should prevent any DBS API to match /_/_/*.

**Comment by yuyiguo** [comment]
something like "dataset=/*/*/FEVT" will also timeout. DBS listDatasets API provides searching on data_tire_name so we will restrict searchs like "datasets?dataset=/*/*/my-tire" to force people using data_tire_name=my-tire search.
@vkuznet , Could you please update DAS too?

**Comment by vkuznet** [comment]
Yuyi,
this will require coding since I'll need to break down dataset path, verify
that tier part is not a pattern, etc. What would happen if user provide tier
pattern? Does API will allow to use it? Also, please confirm that datasets web API
is the same as listDatasets server API, right?

I'll suggest that you should NOT enforce this until I'll implement code in DAS,
otherwise DAS queries will stop working and we'll face angry users.
Valentin.

**Comment by yuyiguo** [comment]
Valentin:

dataset web API is the same as listDatsets server API. The is no restrictions on tire pattern.  
 Yes, I will wait for your green light before I make changes in DBS.
Yuyi

**Comment by vkuznet** [comment]
Here is a patch which implements the logic in DAS: https://github.com/dmwm/DAS/commit/0bb513c4309582f7c710790664e2cb6df970c981

I checked that it works and placed query: 
```dataset run=281728 dataset=/*/*/*RECO```

transforms into the following DBS call:
```
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets/?run_num=281728&detail=True&dataset_access_type=VALID&data_tier_name=%2ARECO
```

**Comment by vkuznet** [comment]
Yuyi, I deployed new DAS version with this change on das-sl6.cern.ch and you can verify that it works as expecting. Just visit:
https://das-sl6.cern.ch/das and place some query, e.g.
dataset run=281728 dataset=/*/*/*RECO
or better use non-existing tier, e.g. dataset run=281728 dataset=/*/*/YUYI
and check the DBS API call in DBS server. it should use data_tier_name parameter.
The implemented logic only use it when dataset path contains a tier or tier pattern and not prim/proc parts.

**Comment by yuyiguo** [comment]
Valentin, 
https://das-sl6.cern.ch/das is your private server, right?  Which dbs server does it connect to? I got site cannot reached error when using browser from fnal.  
Then at cern I used curl, but got 500 error back. How should I access the das server?
curl -k  --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem -H "Accept:application/json" -v "https://das-sl6.cern.ch/das/dataset?run=281728"

**Comment by vkuznet** [comment]
Yuyi, it is my CERN VM, therefore you need to use SSH tunnel to access it.
If you need to access it via cli then you can get das client from
cmsweb.cern.ch/das/cli and then use it and pass proper URL option, see
--help option

**Comment by yuyiguo** [comment]
Got it. Thanks.

**Comment by yuyiguo** [comment]
@vkuznet 

I limited any wildcard in dataset for the listDataset API because it will be much efficient to search on primary, process or datatire separately if any of them has a wildcard. Please update DAS accordingly.

**Comment by vkuznet** [comment]
Yuyi, we updated DASMaps on production/testbed servers and /*/*/* pattern
is no longer in use in DAS calls. Please go ahead and proceed with this
issue for DBS on production servers.
Best,
Valentin.

**Comment by vkuznet** [comment]
Yuyi, I made changes to DAS code to decompose dataset path into three parts if there is a pattern in a path somewhere. The code changes are here: https://github.com/dmwm/DAS/commit/9775fa4c774c45e25c2cdc751acf5829d178fe16
and you may test them using my private DAS VM: https://das-sl6.cern.ch/das/

Please note, even though I made changes within this cycle I can't yet deployed within this release since it requires DASMaps changes and testing, I just don't want to overlap with current release upgrade since it targets changes to new MongoDB and python3 support in DAS code. But in next release we can make it.

Feel free to place some dataset queries into my DAS VM, e.g. dataset=/ZMM*/*/* and monitor API calls on DBS side, you should see that this query will use primary_ds_name, processed_ds_name and data_tier_name parameters instead of dataset, while if you'll place a full dataset name you should get a call to datasets API with dataset name.

I tested changes locally and it seems working fine.

**Comment by yuyiguo** [comment]
Done
